services:
  todomysql:
    image: mysql:8.0
    container_name: todo-mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./django-backend/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build: ./django-backend
    container_name: django-uwsgi
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./django-backend:/app
    ports:
      - "8000:8000"
    depends_on:
      todomysql:
        condition: service_healthy
    env_file:
      - ./django-backend/.env

  frontend:
    build: ./react-frontend
    container_name: react-nginx
    depends_on:
      - backend

  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    container_name: todo-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

volumes:
  mysql-data: